services:
  database:
    image: "postgres:16.9-bullseye"
    container_name: TrelloClone
    ports:
      - ${POSTGRES_PORT}:5432

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Sao_Paulo
